version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/TestBackendAEON
    depends_on:
      - php
      - database

  php:
    build:
      context: dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/TestBackendAEON

  database:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./test.sql:/docker-entrypoint-initdb.d/dump.sql
    env_file:
      - env/database.env
